version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 5
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: '/microsite/'
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 2
    labels:
      - dependencies
