comment: false # Ref: https://docs.codecov.io/docs/pull-request-comments

coverage:
  status:
    project:
      default:
        threshold: 0% # Ref: https://docs.codecov.io/docs/codecovyml-reference#coveragestatus
        target: auto
