app:
  title: Backstage Example App
  baseUrl: http://localhost:3000

backend:
  baseUrl: http://localhost:7000
  listen: 0.0.0.0:7000
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true

organization:
  name: Spotify
