apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: backstage
spec:
  selector:
    matchLabels:
      app: backstage
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
      - name: backstage
        image: 824163854805.dkr.ecr.us-west-2.amazonaws.com/spotify/backstage:latest
        ports:
        - containerPort: 3000