apiVersion: v1
kind: Service
metadata:
  name: backstage-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: alb
    # so the lb doesn't route to the internet
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: backstage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
