apiVersion: v1
kind: Service
metadata:
  name: backstage-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: alb
    # so the lb doesn't route to the internet
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:824163854805:certificate/6a1adb67-9507-4382-a75b-e4dfb3bc70b4
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  type: LoadBalancer
  selector:
    app: backstage
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000

